name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"
    # runs at 12 PM UTC (5:30 PM IST)
    - cron: "0 12 * * *"
  push:
    paths:
      - .github/workflows/**

jobs:
  update-readme:
    name: WakaReadme Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: -#
          SHOW_MASKED_TIME: true
          COMMIT_MESSAGE: "chore: refresh dynamic content"
          IGNORED_LANGUAGES: "JSON YAML INI Text TOML Docker"
          AUTHOR_NAME: "Wakatime"
